### ISSUE TITLE
Login and Sign Up

### ISSUE THREAD

**Issue by jmsfrancies** [ahenmy/TheFriendZone#2]
Hello Team Member,

When I signed up and filled out the profile questionnaire. There wasn't a means of processing my information.

**Comment by mommylocs** [comment]
Thank you for pointing that out. I was going to have everything point to the User page(user home page) but I decided to use MongoDB (still in progress), to see if it can customize the page.

**Comment by jmsfrancies** [comment]
I look forward to the completed project! :-))
